name: todoappv0
description: Clean Code Architecture and Firebase in a simple TodoApp.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.4.0
  bloc: ^7.2.0
  cupertino_icons: ^1.0.2 
  dartz: ^0.10.0
  firebase_auth: ^3.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  get_it: ^7.2.0
  lint: ^1.6.0
  uuid: ^3.0.4

dev_dependencies:
  auto_route_generator: ^2.4.0
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
